### ISSUE TITLE
README debug setup not up to date

### ISSUE THREAD

**Issue by tlegoc** [Mauler125/r5sdk#116]
Title says it all, followed the configuration steps from the README and it doesn't work (VS 2022).

The solution dir is set to build_intermediate, so it wont find /game/r5apex.exe. 

On an unrelated note I have a link error on netconsole as it tries to link to DetourAttach. Probably an error on my end but i'd be happy if someone had a solution.

**Comment by Mauler125** [comment]
Hi tlegoc,

Thanks for the report. I updated the readme as of commit b5f75876a7a5b5e6efafbacb5737335a564ea35f. Our CMake build system automatically sets the working directory relative from the project files, so the readme was indeed outdated.

The NetConsole linker error has also been fixed; this was caused by the inclusion of code that wasn't supposed to be compiled with the NetConsole. If you still encounter errors while compiling the project, please create a new issue ticket and we will investigate it.
