### ISSUE TITLE
p4sync crashes after 3d36c

### ISSUE THREAD

**Issue by Ilses** [Mauler125/r5sdk#121]
Building from p4sync commit [3d36c](https://github.com/Mauler125/r5sdk/commit/3d36c87b0819cb366fc42efda35e4830ce170c62) x64 Release and running r5apex.exe results in a gamesdk.dll crash.

I am able to run the preceding p4sync commit 02087 without issue, so I believe the refactor introduced a static initialization order fiasco. I locally fixed `CreateGlobalMemAlloc` and `g_pMemAllocSingleton` initialization; afterwards, the gamesdk.dll crash is no longer present but the game startup hangs indefinitely, so there are likely more issues. Ref crash log:

[apex_crash.txt](https://github.com/user-attachments/files/15519352/apex_crash.txt)

To be sure this wasn't fixed by some later commit, I tried jumping forward to 3bb4e and applied the same local fixes to tier0\memstd.h. However, `CModule::GetExportedSymbol()` fails to map the following three symbols: 

`g_ThreadMainThreadID`
`g_ThreadServerFrameThreadID`
`LauncherMain`

This because the inner `pImageExportDirectory->NumberOfNames` loop only finds the following 5 names:

```
WinMain
AmdPowerXpressRequestHighPerformance
CreateGlobalMemAlloc
g_pMemAllocSingleton
g_pCmdLine
```

The result is another crash since `v_LauncherMain = nullptr` which triggers the detours attach failure assert.

Let me know if there's anything else I could try that would be helpful.

**Comment by Mauler125** [comment]
Hi Ilses,

The p4sync branch underwent many changes on perforce, before being synced to git due to popular demand. The SDK hasn't been finished yet for the next release. The internals have breaking changes with the old (currently released) engine binary.

The reason why the game crashes is because I had changed up the exports table of the executable:

- LauncherMain is now exported instead of WinMain due to the inability to gracefully shutdown the SDK from WinMain (which calls LauncherMain under the hood).

- The thread ID globals (part of the embedded Tier0 library) were exported as we had issues with concurrent ConVar/ConCommand between the main and server frame threads. This was a very rare issue however. These are now used to check ConVar/ConCommand marked 'FCVAR_SERVER_FRAME_THREAD' (see ThreadInServerFrameThread()), and latch them if 'g_ThreadServerFrameThreadID' holds a valid Job ID.

We have recently launched a beta test for users to test the new SDK and scripts, so we could catch the last few bugs. You need the following sound banks, sound DLL's and engine executable in order to launch this SDK: https://github.com/SlaveBuild/N1094_Playtest/releases/tag/v10.0.47.7

download all the files as-is, and extract the zip files in the root of the game install (replace all files if asked).
NOTE: these are development binaries; ASLR (Address Space Layout Randomization) has been disabled on some binaries.

**Comment by Ilses** [comment]
Thanks! In that case, I'll try out using the beta test files
